"""LaTeX tables for the paper, generated from committed results -- never typed.

Same rule as make_tables.py: a number that is copied by hand can drift from the
data without anyone noticing, so every table the paper prints is written here.
Sources:

  results/ladder_300k/, results/ladder_150k/   per-run ladder summaries
  results/single_change_300k/                  single-change evaluation pass
  results/reordered_ladder_300k/               reordered-ladder evaluation pass
  robust_stats.py                              95% CIs (same functions, same seeds,
                                               so the paper and results/tables agree)
  results/tables/grid_stats_300k.md            declared Holm families (parsed;
                                               re-running 10^5 permutations to
                                               reprint numbers already generated
                                               would add nothing)
  test_target_effect.analyse                   goal-object control

Wording rule (Vishwas, 2026-09-29): success RATES and DROPS in success rate, in
percentage points. Never "loss" or "share of success lost"; a relative drop
appears only in brackets.

    python scripts/make_paper_tables.py        # -> paper_v2/generated/*.tex
"""
from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Dict, List

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

import make_tables as mt  # noqa: E402
import robust_stats as rs  # noqa: E402
from config import AGENT_NAME, LADDER_150K, LADDER_300K, REORDERED_LADDER  # noqa: E402

OUT = ROOT / "paper_v2" / "generated"   # the first draft in paper/ is frozen
TABLES = ROOT / "results" / "tables"
NAME = AGENT_NAME
# The stats files print the same display names; map them back to code names.
STATS_NAME = {v: k for k, v in AGENT_NAME.items()}
GROUPS = [("Model-free, encoder trained from scratch", ["ppo", "ppo_aug"]),
          ("Model-free, frozen pretrained encoder", ["ppo_jepa", "ppo_mae", "ppo_dino"]),
          ("World model, encoder trained from scratch", ["dreamerv3", "tdmpc2"]),
          ("World model, frozen pretrained encoder", ["tdmpc2_dino"])]
HEADER = "% Generated by scripts/make_paper_tables.py -- do not edit by hand.\n"


def pct(v: float) -> str:
    v = 100 * v
    txt = f"{0 if abs(v) < 0.5 else v:.0f}"
    return "$-$" + txt[1:] if txt.startswith("-") else txt


def signed(v: float, fmt: str) -> str:
    """Signed number with a typographic minus."""
    txt = format(v, fmt)
    return "$-$" + txt[1:] if txt.startswith("-") else txt


def p_tex(p: float) -> str:
    return "$<$0.0001" if p < 1e-4 else f"{p:.4f}" if p < 0.001 else f"{p:.3f}"


def r0(v: float) -> str:
    """Whole number with a typographic minus; never '-0'."""
    txt = f"{v:.0f}"
    if txt == "-0":
        txt = "0"
    return "$-$" + txt[1:] if txt.startswith("-") else txt


def ci_pts(c) -> str:
    """Points with a small CI: 42 [36, 48]."""
    return f"{r0(c[0])} {{\\scriptsize[{r0(c[1])}, {r0(c[2])}]}}"


def ci_rate(c) -> str:
    """Success rate with a small CI: 0.52 [0.45, 0.58]."""
    return f"{c[0]:.2f} {{\\scriptsize[{c[1]:.2f}, {c[2]:.2f}]}}"


def dagger(rec: Dict) -> str:
    return r"$^\dagger$" if "drop_points_every_run" in rec else ""


def grouped(rows_for, ncols: int) -> List[str]:
    """Body rows, grouped by agent class with an italic group heading."""
    L = []
    for gi, (title, members) in enumerate(GROUPS):
        if gi:
            L.append(r"\addlinespace[2pt]")
        L.append(rf"\multicolumn{{{ncols}}}{{@{{}}l}}{{\textit{{{title}}}}} \\")
        for b in members:
            L.append(rows_for(b))
    return L


# ---------------------------------------------------------------- main ladder
def tab_main() -> str:
    """Success rate with 95% CI along the original ladder (every run)."""
    res = rs.ladder(LADDER_300K)["agents"]
    L = [HEADER, r"\begin{tabular}{@{}lcccc@{}}", r"\toprule",
         r"Agent & House A & L1 & L2 & L3 \\", r"\midrule"]
    L += grouped(lambda b: f"\\quad {NAME[b]} & " + " & ".join(
        ci_rate(res[b][r]["success"]) for r in mt.RUNGS) + r" \\", 5)
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def tab_drop() -> str:
    """Drop in success rate from house A, points with 95% CI; relative in brackets."""
    res = rs.ladder(LADDER_300K)["agents"]
    L = [HEADER, r"\begin{tabular}{@{}lccc@{}}", r"\toprule",
         r" & \multicolumn{3}{c}{Drop in success rate from house A (points)} \\",
         r"\cmidrule(l){2-4}", r"Agent & L1 & L2 & L3 \\", r"\midrule"]
    L += grouped(lambda b: f"\\quad {NAME[b]}{dagger(res[b]['L1'])} & " + " & ".join(
        f"{ci_pts(res[b][r]['drop_points'])} ({r0(100 * res[b][r]['relative_drop'])}\\%)"
        for r in mt.SHIFTED) + r" \\", 4)
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- reordered
def tab_reordered() -> str:
    """Success rate with 95% CI along the reordered (cumulative) ladder, every run."""
    res = rs.reordered()["agents"]
    codes = [c for c, _n in REORDERED_LADDER]
    L = [HEADER, r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
         r"Agent & House A & R1 & R2 & R3 & R4 \\",
         r" & & clutter & + lighting \& sky & + object looks & + walls, floor \& ceiling \\",
         r"\midrule"]
    L += grouped(lambda b: f"\\quad {NAME[b]} & " + " & ".join(
        ci_rate(res[b][c]["success"]) for c in codes) + r" \\", 6)
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


# ------------------------------------------------------------- single change
def tab_single() -> str:
    """Drop (points) when ONE factor changes; bold = each agent's largest drop."""
    res = rs.single_change()
    ag = res["agents"]
    cols = [("F_light", "Light"), ("F_sky", "Sky"), ("F_mat", "Walls/floor"),
            ("F_obj", "Objects"), ("F_tgt", "Goal"), ("F_clut", "Clutter")]
    L = [HEADER, r"\begin{tabular}{@{}lcccccc@{}}", r"\toprule",
         r" & \multicolumn{3}{c}{L1 factors} & \multicolumn{2}{c}{L2 factors} & L3 \\",
         r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(l){7-7}",
         "Agent & " + " & ".join(h for _k, h in cols) + r" \\", r"\midrule"]
    for a in ag:
        vals = {k: ag[a][k]["drop_points"][0] for k, _h in cols}
        best = max(vals, key=vals.get)
        cells = [rf"\textbf{{{r0(vals[k])}}}" if k == best else r0(vals[k]) for k, _h in cols]
        L.append(f"{NAME[a]}{dagger(ag[a]['F_mat'])} & " + " & ".join(cells) + r" \\")
    L.append(r"\midrule")
    mo = res["mean_over_agents"]
    L.append(r"Mean & " + " & ".join(ci_pts(mo[k]) for k, _h in cols) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------ budgets
def tab_budget() -> str:
    """House-A and L2 success, and the drop at L2 in points, at both budgets."""
    agents = ["ppo", "ppo_aug", "dreamerv3", "tdmpc2"]
    by = {}
    for grid, tag in ((LADDER_150K, "150k"), (LADDER_300K, "300k")):
        res = rs.ladder(grid)["agents"]
        for b in agents:
            by[(b, tag)] = (res[b]["A"]["success"][0], res[b]["L2"]["success"][0],
                            res[b]["L2"]["drop_points"], res[b]["L2"]["runs"])
    L = [HEADER, r"\begin{tabular}{@{}lcccccc@{}}", r"\toprule",
         r" & \multicolumn{3}{c}{150k steps} & \multicolumn{3}{c}{300k steps} \\",
         r"\cmidrule(lr){2-4}\cmidrule(l){5-7}",
         r"Agent & A & L2 & drop (pts) & A & L2 & drop (pts) \\", r"\midrule"]
    for b in agents:
        c = []
        for t_ in ("150k", "300k"):
            a, l2, drop, n = by[(b, t_)]
            mark = rf"$^{{\dagger{n}}}$" if n < 25 else ""
            c += [f"{a:.2f}", f"{l2:.2f}", ci_pts(drop) + mark]
        L.append(f"{NAME[b]} & " + " & ".join(c) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


# --------------------------------------------------------------- ingredients
# (X, Y, group): what changing X into Y buys. Gap = drop(X) - drop(Y), so a
# positive gap means Y drops less.
COMPARISONS = [
    ("ppo", "ppo_aug", "Colour augmentation"),
    ("ppo", "tdmpc2", "A world model, encoder learned from scratch"),
    ("ppo", "dreamerv3", "A world model, encoder learned from scratch"),
    ("ppo", "ppo_jepa", "A frozen pretrained encoder"),
    ("ppo", "ppo_mae", "A frozen pretrained encoder"),
    ("ppo", "ppo_dino", "A frozen pretrained encoder"),
    ("tdmpc2", "tdmpc2_dino", "Both: a world model on the frozen DINOv2 encoder"),
    ("ppo_dino", "tdmpc2_dino", "Both: a world model on the frozen DINOv2 encoder"),
]


def _pair(res: Dict, table: str, x: str, y: str, rung: str):
    """Gap or P for (x, y) whichever order robust_stats stored it in."""
    from config import AGENT_ORDER
    if AGENT_ORDER.index(x) < AGENT_ORDER.index(y):
        return res[table][f"{x}>{y}@{rung}"], False
    return res[table][f"{y}>{x}@{rung}"], True


def tab_compare() -> str:
    """Gap in drop (points, 95% CI) for each ingredient, and P(Y beats X) at L2."""
    res = rs.ladder(LADDER_300K)
    L = [HEADER, r"\begin{tabular}{@{}lcccc@{}}", r"\toprule",
         r" & \multicolumn{3}{c}{Reduction in drop (points)} & $P$(Y beats X) \\",
         r"\cmidrule(lr){2-4}\cmidrule(l){5-5}",
         r"From X to Y & L1 & L2 & L3 & at L2 \\", r"\midrule"]
    group = None
    for x, y, g in COMPARISONS:
        if g != group:
            if group is not None:
                L.append(r"\addlinespace[2pt]")
            L.append(rf"\multicolumn{{5}}{{@{{}}l}}{{\textit{{{g}}}}} \\")
            group = g
        cells = []
        for rung in mt.SHIFTED:
            v, flipped = _pair(res, "gap_in_drop", x, y, rung)
            cells.append(ci_pts([-v[0], -v[2], -v[1]] if flipped else v))
        pv, flipped = _pair(res, "prob_improvement", x, y, "L2")
        # stored as P(first beats second); we want P(Y beats X)
        pyx = pv if flipped else [1 - pv[0], 1 - pv[2], 1 - pv[1]]
        cells.append(f"{pyx[0]:.2f} {{\\scriptsize[{pyx[1]:.2f}, {pyx[2]:.2f}]}}")
        L.append(f"\\quad {NAME[x]} $\\to$ {NAME[y]} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def tab_rgb() -> str:
    """Within-house rank correlation between colour shift and drop, by kind of change."""
    import json
    res = json.loads((TABLES / "rgb_shift_analysis.json").read_text())

    def cell(key):
        rho, p = (res["within"] if key.count("|") == 1 else res["by_kind"])[key]
        p_txt = "$<$0.001" if p < 0.001 else f"{p:.3f}"
        return f"{signed(rho, '+.2f')} {{\\scriptsize({p_txt})}}"
    L = [HEADER, r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
         r" & \multicolumn{3}{c}{Colour shift (W1)} & \multicolumn{2}{c}{Per-pixel difference} \\",
         r"\cmidrule(lr){2-4}\cmidrule(l){5-6}",
         r"Agent & all changes & no repaint & repaint & all changes & no repaint \\", r"\midrule"]
    for a in res["agents"] + ["all"]:
        name = "Mean over agents" if a == "all" else NAME[a]
        if a == "all":
            L.append(r"\midrule")
        L.append(f"{name} & " + " & ".join([
            cell(f"w1_mean|{a}"), cell(f"no_repaint|w1_mean|{a}"), cell(f"repaint|w1_mean|{a}"),
            cell(f"mean_abs_diff|{a}"), cell(f"no_repaint|mean_abs_diff|{a}")]) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


# ---------------------------------------------------------------- appendix
def tab_houses() -> str:
    import json
    from config import pair_dir
    meta = mt.pair_meta()
    L = [HEADER, r"\begin{tabular}{@{}lcccccc@{}}", r"\toprule",
         r"Pair & Target & Reachable cells & Clutter kept & Target swapped & "
         r"Max.\ path shift L1 (m) & Max.\ path shift L2/L3 (m) \\", r"\midrule"]
    for pid in sorted(meta, key=lambda p: meta[p]["cells"]):
        m = meta[pid]
        v = json.loads((pair_dir(pid) / "verification.json").read_text())
        lv = v.get("levels", v)

        def shift(level):
            rec = lv.get(level, {}) if isinstance(lv, dict) else {}
            val = rec.get("max_shortest_path_delta")
            return f"{val:.2f}" if isinstance(val, (int, float)) else "--"
        l23 = [shift("L2"), shift("L3")]
        L.append(f"{pid.replace('pair', 'P')} & {m['target']} & {m['cells']} & {m['clutter']} & "
                 f"{'yes' if m['swappable'] else 'no'} & {shift('L1')} & {' / '.join(l23)} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def tab_perhouse() -> str:
    d = mt.load(LADDER_300K)
    meta = mt.pair_meta()
    pairs = sorted(d.pair.unique(), key=lambda p: meta[p]["cells"])
    L = [HEADER, r"\begin{tabular}{@{}ll" + "c" * len(mt.RUNGS) + "@{}}", r"\toprule",
         "Pair & Agent & " + " & ".join(mt.RUNGS) + r" \\", r"\midrule"]
    for i, pid in enumerate(pairs):
        if i:
            L.append(r"\midrule")
        m = meta[pid]
        label = rf"\multirow{{{len(mt.ORDER)}}}{{*}}{{\shortstack[l]{{{pid.replace('pair', 'P')}\\{m['target']}}}}}"
        for j, b in enumerate(mt.ORDER):
            s = d[(d.baseline == b) & (d.pair == pid)]
            cells = [f"{s[s.rung == r].success.mean():.2f}$\\pm${s[s.rung == r].success.std():.2f}"
                     for r in mt.RUNGS]
            L.append(f"{label if j == 0 else ''} & {NAME[b]} & " + " & ".join(cells) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def tab_target() -> str:
    within, _per_house = mt.target_results("300k")
    gc = rs.goal_control()
    L = [HEADER, r"\begin{tabular}{@{}lcccc@{}}", r"\toprule",
         r"Agent & L2noT (goal unchanged) & L2 (goal changed) & Effect (pts) & $p$ (Holm) \\",
         r"\midrule"]
    for b in mt.ORDER:
        r = within[b]
        L.append(f"{NAME[b]} & {r['L2noT']:.2f} & {r['L2']:.2f} & {ci_pts(gc[b]['effect_points'])} & "
                 f"{p_tex(r['p_holm'])} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


FAM_RE = re.compile(r"^\s*(.+?)\s+vs\s+(.+?)\s+([+-]\d+\.\d)%\s+p=([\d.]+)\s+Holm p=([\d.]+)")


def families(path: Path, which: str) -> Dict[str, List[tuple]]:
    """Parse the declared Holm families from the competency-filtered block."""
    text = path.read_text()
    block = text.split("RUNS WITH HOUSE-A SUCCESS >= 0.5")[1]
    fams: Dict[str, List[tuple]] = {}
    cur = None
    for line in block.splitlines():
        if "FAMILY" in line:
            cur = line.strip().split(" — ")[0]
            fams[cur] = []
        elif cur:
            m = FAM_RE.match(line)
            if m:
                a, b = STATS_NAME[m.group(1).strip()], STATS_NAME[m.group(2).strip()]
                fams[cur].append((a, b, float(m.group(3)), float(m.group(4)), float(m.group(5))))
    return fams


def tab_families() -> str:
    fams = families(TABLES / "grid_stats_300k.md", "300k")
    label = {"ALL-PAIRS FAMILY": "All pairs, success at L2 (28 comparisons)",
             "ORIGINAL-FOUR FAMILY": "Original four agents, success at L2 (6; fixed before any pretrained encoder was run)",
             "DINOv2 FAMILY": "PPO+DINOv2 vs.\\ each agent that existed when fixed, success at L1 (6)",
             "TD-MPC2+DINOv2 FAMILY": "TD-MPC2+DINOv2 vs.\\ each agent, success at L1 (7)"}
    L = [HEADER, r"\begin{tabular}{@{}llccc@{}}", r"\toprule",
         r"Agent 1 & Agent 2 & Gap in relative drop (pts) & $p$ & $p$ (Holm) \\", r"\midrule"]
    for i, (key, rows) in enumerate(fams.items()):
        if i:
            L.append(r"\midrule")
        L.append(rf"\multicolumn{{5}}{{@{{}}l}}{{\textit{{{label.get(key, key)}}}}} \\")
        for a, b, gap, p, ph in rows:
            ph_txt = r"\textbf{" + p_tex(ph) + "}" if ph < 0.05 else p_tex(ph)
            L.append(f"{NAME[a]} & {NAME[b]} & {signed(gap, '+.1f')} & {p_tex(p)} & {ph_txt} \\\\")
    L += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(L) + "\n"


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, fn in [("tab_main", tab_main), ("tab_drop", tab_drop),
                     ("tab_reordered", tab_reordered), ("tab_single", tab_single),
                     ("tab_compare", tab_compare), ("tab_rgb", tab_rgb),
                     ("tab_budget", tab_budget), ("tab_houses", tab_houses),
                     ("tab_perhouse", tab_perhouse), ("tab_target", tab_target),
                     ("tab_families", tab_families)]:
        out = OUT / f"{name}.tex"
        out.write_text(fn())
        print(f"  wrote {out}")


if __name__ == "__main__":
    main()
