"""Paper tables from the grid, generated -- never transcribed.

Every number in the paper comes from here, so a table can be regenerated from
the committed CSVs and can never drift from them. For each budget:

  results/tables/grid_main_<budget>.md     main-body tables, pooled over houses
  results/tables/grid_by_pair_<budget>.md  appendix: every house, every agent type

Rules the tables follow:
  * Pooled means are always printed WITH their range across houses. PPO's L1
    damage runs from 6% to 95% across the five houses, so a pooled mean alone
    would describe no house.
  * In-domain success (house A) sits beside every transfer number.
  * Success rates use every agent. The share of house-A success LOST is a ratio,
    so runs with house-A success < 0.5 are left out of it (rule fixed
    2026-09-05); the number of runs counted is printed.
  * A, L1, L2, L3 come from the committed grid (the original agents). The L2noT
    control is reported separately, from `scripts/test_target_effect.py`, where
    each agent is compared with itself in one evaluation.

    python scripts/make_tables.py                 # 300k (headline)
    python scripts/make_tables.py --grid grid     # 150k (appendix)
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import pandas as pd

from config import GenerationConfig, TABLES_DIR, pair_dir

RUNGS = ["A", "L1", "L2", "L3"]
SHIFTED = ["L1", "L2", "L3"]
ORDER = ["ppo", "ppo_aug", "ppo_jepa", "ppo_mae", "ppo_dino", "dreamerv3", "tdmpc2"]
NICE = {"ppo": "PPO", "ppo_aug": "PPO + aug", "ppo_jepa": "PPO + JEPA",
        "ppo_mae": "PPO + MAE", "ppo_dino": "PPO + DINOv2",
        "dreamerv3": "DreamerV3", "tdmpc2": "TD-MPC2"}
CLASS = {"ppo": "model-free, vision trained here",
         "ppo_aug": "model-free + augmentation",
         "ppo_jepa": "frozen pretrained encoder (predicts representations)",
         "ppo_mae": "frozen pretrained encoder (predicts pixels)",
         "ppo_dino": "frozen pretrained encoder (self-distillation, LVD-142M)",
         "dreamerv3": "world model (latent must redraw the scene)",
         "tdmpc2": "world model (no decoder)"}
MIN_A = 0.5
RUNG_NAME = {"A": "A (training house)", "L1": "L1 walls/floor/light",
             "L2": "L2 + objects & target", "L3": "L3 + clutter"}


def budget_tag(grid: str) -> str:
    return "150k" if grid == "grid" else f"{int(grid.split('_')[1]) // 1000}k"


def load(grid: str) -> pd.DataFrame:
    """One row per (agent run, rung) from the committed grid tree."""
    rows = []
    for f in sorted(glob.glob(str(ROOT / "results" / grid / "*" / "*" / "*_transfer_summary.csv"))):
        p = Path(f)
        baseline = p.parents[1].name
        pair, seed = p.parent.name.split("_seed")
        df = pd.read_csv(f).set_index("level")
        A, AS = df.loc["A", "success_rate"], df.loc["A", "spl"]
        for rung in RUNGS:
            if rung not in df.index:
                raise ValueError(f"{f} has no {rung} row")
            rows.append(dict(
                baseline=baseline, pair=pair, seed=int(seed), rung=rung,
                A_success=A, A_spl=AS,
                success=df.loc[rung, "success_rate"], spl=df.loc[rung, "spl"],
                drop=(A - df.loc[rung, "success_rate"]) / A if A else float("nan"),
                spl_drop=(AS - df.loc[rung, "spl"]) / AS if AS else float("nan"),
            ))
    return pd.DataFrame(rows)


def pair_meta() -> dict:
    out = {}
    for i in range(GenerationConfig().n_pairs):
        pid = f"pair{i}"
        v = json.loads((pair_dir(pid) / "verification.json").read_text())
        s = json.loads((pair_dir(pid) / "safe_assets.json").read_text())
        t = json.loads((pair_dir(pid) / "task_config.json").read_text())
        l3 = json.loads((pair_dir(pid) / "l3_prune.json").read_text())
        out[pid] = dict(cells=v["reference"]["n_reachable"],
                        target=t["target_object_type"],
                        swappable=bool(s.get("target_swappable")),
                        clutter=l3.get("n_kept"))
    return out


def pooled(s: pd.DataFrame, col: str, pct: bool) -> str:
    """mean over runs, with (min-max) of the per-house means."""
    per_house = s.groupby("pair")[col].mean()
    f = (lambda v: f"{100 * v:.0f}%") if pct else (lambda v: f"{v:.2f}")
    return f"{f(s[col].mean())} ({f(per_house.min())}–{f(per_house.max())})"


def main_table(d: pd.DataFrame, tag: str, target: dict) -> str:
    present = [b for b in ORDER if b in set(d.baseline)]
    n_pairs, n_seeds = d.pair.nunique(), d.seed.nunique()
    L = [f"# Grid — main tables ({tag} environment steps)", "",
         "Generated by `scripts/make_tables.py` — do not edit by hand. "
         f"{n_pairs} house pairs × {n_seeds} training seeds per agent type. "
         "Brackets = lowest–highest of the per-house means.", "",
         "## 1. Success rate (every agent)", "",
         "| agent | type | agents | " + " | ".join(RUNG_NAME[r] for r in RUNGS) + " |",
         "|---|---|---|" + "---|" * len(RUNGS)]
    for b in present:
        sub = d[d.baseline == b]
        n = sub[sub.rung == "A"].shape[0]
        L.append(f"| {NICE[b]} | {CLASS[b]} | {n} | " + " | ".join(
            pooled(sub[sub.rung == r], "success", pct=False) for r in RUNGS) + " |")

    L += ["", f"## 2. Share of house-A success lost (runs with house-A success ≥ {MIN_A})", "",
          "| agent | runs counted | house-A success | " +
          " | ".join(RUNG_NAME[r] for r in SHIFTED) + " |",
          "|---|---|---|" + "---|" * len(SHIFTED)]
    for b in present:
        sub = d[(d.baseline == b) & (d.A_success >= MIN_A)]
        n = sub[sub.rung == "A"].shape[0]
        total = d[(d.baseline == b) & (d.rung == "A")].shape[0]
        L.append(f"| {NICE[b]} | {n} of {total} | {pooled(sub[sub.rung == 'A'], 'success', pct=False)} | "
                 + " | ".join(pooled(sub[sub.rung == r], "drop", pct=True) for r in SHIFTED) + " |")

    L += ["", f"## 3. Same, SPL (path efficiency; runs with house-A success ≥ {MIN_A})", "",
          "| agent | house-A SPL | " + " | ".join(RUNG_NAME[r] for r in SHIFTED) + " |",
          "|---|---|" + "---|" * len(SHIFTED)]
    for b in present:
        sub = d[(d.baseline == b) & (d.A_success >= MIN_A)]
        L.append(f"| {NICE[b]} | {pooled(sub[sub.rung == 'A'], 'spl', pct=False)} | "
                 + " | ".join(pooled(sub[sub.rung == r], "spl_drop", pct=True) for r in SHIFTED) + " |")

    if target:
        L += ["", "## 4. Target control: does changing ONLY the target's look hurt?", "",
              "Each agent compared with itself in one evaluation; 20 agents per type in the four "
              f"houses where the target is swapped. Exact test; p Holm-corrected over {len(target)} agent types. "
              "Full detail: `results/tables/target_effect_tests.md`.", "",
              "| agent | success, target unchanged (L2noT) | success, target changed (L2) | difference | p |",
              "|---|---|---|---|---|"]
        for b in present:
            r = target[b]
            p = r["p_holm"]
            p_txt = "<0.0001" if p < 1e-4 else f"{p:.3f}"
            L.append(f"| {NICE[b]} | {r['L2noT']:.2f} | {r['L2']:.2f} | {r['effect']:+.2f} | {p_txt} |")
    return "\n".join(L) + "\n"


def by_pair_table(d: pd.DataFrame, meta: dict, tag: str, per_house_target: dict) -> str:
    L = [f"# Grid — per-house breakdown ({tag} environment steps, appendix)", "",
         "Generated by `scripts/make_tables.py` — do not edit by hand. "
         "Mean ± s.d. over the 5 training seeds, every agent. `target swapped` records "
         "whether the target had an alternative asset with the same footprint; where it did "
         "not (pair2), L2 changes everything except the target.", ""]
    pairs = sorted(d.pair.unique(), key=lambda p: meta[p]["cells"])
    present = [b for b in ORDER if b in set(d.baseline)]
    for pid in pairs:
        m = meta[pid]
        L += [f"## {pid} — {m['target']}, {m['cells']} reachable cells, "
              f"{m['clutter']} distractors, target swapped at L2: "
              f"**{'yes' if m['swappable'] else 'NO'}**", "",
              "| agent | A success | L1 | L2 | L3 | A SPL | L1 | L2 | L3 |",
              "|---|---|---|---|---|---|---|---|---|"]
        for b in present:
            s = d[(d.baseline == b) & (d.pair == pid)]
            cells = []
            for col in ("success", "spl"):
                for rung in RUNGS:
                    r = s[s.rung == rung][col]
                    cells.append(f"{r.mean():.2f} ± {r.std():.2f}")
            L.append("| " + NICE[b] + " | " + " | ".join(cells) + " |")
        if per_house_target:
            L += ["", "Target control (same agent, one evaluation; mean over 5 agents):", "",
                  "| agent | L2noT success | L2 success | difference |", "|---|---|---|---|"]
            for b in present:
                l2n, l2 = per_house_target[b][pid]
                L.append(f"| {NICE[b]} | {l2n:.2f} | {l2:.2f} | {l2n - l2:+.2f} |")
        L.append("")
    return "\n".join(L) + "\n"


def target_results(tag: str):
    """L2noT results for the 300k grid only (the 150k grid has no L2noT rung)."""
    if tag != "300k":
        return {}, {}
    import test_target_effect as tte
    _l, res = tte.analyse("success_rate", draws=200_000, seed=20260915)
    data = tte.load("success_rate")
    per_house = {a: {h: (sum(r[2] for r in rows) / len(rows), sum(r[3] for r in rows) / len(rows))
                     for h, rows in data[a].items()} for a in data}
    return res["within"], per_house


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--grid", default="grid_300000",
                    help="results/<grid> tree: grid_300000 (headline) or grid (150k)")
    args = ap.parse_args()
    d = load(args.grid)
    if d.empty:
        raise SystemExit(f"no results under results/{args.grid}/")
    counts = d[d.rung == "A"].groupby("baseline").size()
    if set(counts) != {25}:
        raise SystemExit(f"incomplete grid, cells per agent: {dict(counts)}")
    tag = budget_tag(args.grid)
    sys.path.insert(0, str(ROOT / "scripts"))
    target, per_house = target_results(tag)
    meta = pair_meta()
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    for name, text in ((f"grid_main_{tag}.md", main_table(d, tag, target)),
                       (f"grid_by_pair_{tag}.md", by_pair_table(d, meta, tag, per_house))):
        (TABLES_DIR / name).write_text(text)
        print(f"  wrote {TABLES_DIR / name}")
    print(f"  cells per agent: {dict(counts)}")


if __name__ == "__main__":
    main()
