"""What each single change costs — the table, generated.

`scripts/test_single_change.py` answers whether differences are real. This
answers how big they are, and it exists because those numbers were briefly
quoted from a throwaway script: every number the paper prints has to come from
a committed artifact, or it can drift from the data without anyone noticing.

Three things come out of one evaluation pass (`results/factor_300000/`), in
which every trained agent was measured in all twelve houses:

  1. THE RANKING. Share of house-A success lost when exactly ONE thing changes,
     per agent and averaged across them. This is what the cumulative ladder
     cannot say: L2 contains L1, so the ladder can only report totals.
  2. THE PARTS AGAINST THE WHOLE. Sum of the individual losses versus the loss
     of the cumulative rung that contains them. Equal means the changes act
     independently; less means damage saturates (the agent was already broken);
     more means the combination is worse than its pieces.
  3. THE PER-HOUSE SPREAD, for the change that dominates. Pooled means hide a
     range from a few percent to most of the task.

Damage is a ratio, so runs whose house-A success is below 0.5 are left out of
it (the rule fixed 2026-09-05) and the count kept is printed.

    python scripts/summarize_single_change.py   # -> results/tables/single_change_summary.md
"""
from __future__ import annotations

import argparse
import csv
import glob
import sys
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from config import TABLES_DIR  # noqa: E402
from test_single_change import AGENTS, GRID, MIN_A, NICE  # noqa: E402

# code name -> (column header, plain description)
SINGLE = [
    ("F_light", "lighting", "light colour and brightness"),
    ("F_sky", "sky", "the sky seen through the windows"),
    ("F_mat", "walls/floor", "wall, floor and ceiling materials"),
    ("F_obj", "objects (not target)", "every object's look except the target's"),
    ("F_tgt", "target only", "the target's look, nothing else"),
    ("F_objall", "all objects", "every object's look, target included"),
    ("F_clut", "clutter", "clutter added, nothing else changed"),
]
CUMULATIVE = ["L1", "L2noT", "L2", "L3"]
# (cumulative rung, the single changes it is built from)
DECOMPOSE = [
    ("L1", ["F_mat", "F_light", "F_sky"]),
    ("L2noT", ["F_mat", "F_light", "F_sky", "F_obj"]),
    ("L2", ["F_mat", "F_light", "F_sky", "F_objall"]),
    ("L3", ["F_mat", "F_light", "F_sky", "F_objall", "F_clut"]),
]
# The four single changes that are one rung's whole change, for the ranking.
RANKED = ["F_clut", "F_light", "F_obj", "F_sky", "F_tgt", "F_mat"]


def load() -> Dict[Tuple[str, str, int, str], float]:
    out: Dict[Tuple[str, str, int, str], float] = {}
    for f in sorted(glob.glob(str(ROOT / "results" / GRID / "*" / "*" / "*_transfer_summary.csv"))):
        p = Path(f)
        agent = p.parents[1].name
        pair, seed = p.parent.name.split("_seed")
        with p.open(newline="") as fh:
            for row in csv.DictReader(fh):
                out[(agent, pair, int(seed), row["level"])] = float(row["success_rate"])
    if not out:
        raise SystemExit(f"no results under results/{GRID}/")
    return out


def lost(data, agent: str, rung: str) -> List[Tuple[str, float]]:
    """(house, share of house-A success lost) for every competent run."""
    rows = []
    for (a, pair, seed, r), v in data.items():
        if a != agent or r != "A" or v < MIN_A:
            continue
        b = data.get((agent, pair, seed, rung))
        if b is None:
            continue
        rows.append((pair, (v - b) / v))
    return rows


def mean(xs) -> float:
    xs = list(xs)
    return sum(xs) / len(xs) if xs else float("nan")


def pct(x: float) -> str:
    return "—" if x != x else f"{100 * x:.0f}%"


def build() -> str:
    data = load()
    present = [a for a in AGENTS if any(k[0] == a for k in data)]

    L = ["# What each single change costs", "",
         "Generated by `scripts/summarize_single_change.py` — do not edit by hand. "
         f"One evaluation pass (`results/{GRID}/`), 300k training steps, every agent "
         "measured in all twelve houses. Damage = share of that run's own house-A "
         f"success lost; runs below house-A {MIN_A} are excluded from the ratio.", "",
         "## 1. One change at a time", "",
         "| agent | " + " | ".join(h for _k, h, _d in SINGLE) + " |",
         "|---|" + "---|" * len(SINGLE)]
    per_agent: Dict[str, Dict[str, float]] = {}
    for a in present:
        per_agent[a] = {k: mean(v for _h, v in lost(data, a, k)) for k, _h, _d in SINGLE}
        L.append(f"| {NICE[a]} | " + " | ".join(pct(per_agent[a][k]) for k, _h, _d in SINGLE) + " |")

    L += ["", "**The ranking**, averaged over the "
          f"{len(present)} agents (range = least to most affected agent):", "",
          "| change, on its own | mean | range across agents |", "|---|---|---|"]
    ranked = sorted(RANKED, key=lambda k: mean(per_agent[a][k] for a in present))
    for k in ranked:
        vals = [per_agent[a][k] for a in present]
        desc = next(d for kk, _h, d in SINGLE if kk == k)
        L.append(f"| {desc} | **{pct(mean(vals))}** | {pct(min(vals))} – {pct(max(vals))} |")

    L += ["", "## 2. Do the parts add up to the whole?", "",
          "Predicted = the individual losses added together; actual = the cumulative "
          "rung that contains them, measured in the same pass. Less than predicted means "
          "damage saturates; more means the combination costs extra.", "",
          "| agent | " + " | ".join(f"{r} predicted / actual" for r, _p in DECOMPOSE) + " |",
          "|---|" + "---|" * len(DECOMPOSE)]
    for a in present:
        cells = []
        for rung, parts in DECOMPOSE:
            pred = sum(per_agent[a][p] for p in parts)
            act = mean(v for _h, v in lost(data, a, rung))
            cells.append(f"{pct(pred)} / **{pct(act)}**")
        L.append(f"| {NICE[a]} | " + " | ".join(cells) + " |")

    L += ["", "## 3. The dominant change, house by house", "",
          "`F_mat` — repainting walls, floor and ceiling — with nothing else changed.", "",
          "| agent | " + " | ".join(sorted({k[1] for k in data})) + " |",
          "|---|" + "---|" * len(sorted({k[1] for k in data}))]
    houses = sorted({k[1] for k in data})
    for a in present:
        by_house = {}
        for h, v in lost(data, a, "F_mat"):
            by_house.setdefault(h, []).append(v)
        L.append(f"| {NICE[a]} | " + " | ".join(pct(mean(by_house.get(h, []))) for h in houses) + " |")

    L += ["", "## 4. Runs counted", "",
          "| agent | competent runs (house-A ≥ 0.5) | of |", "|---|---|---|"]
    for a in present:
        tot = len({(p, s) for (ag, p, s, r) in data if ag == a and r == "A"})
        kept = len(lost(data, a, "F_mat"))
        L.append(f"| {NICE[a]} | {kept} | {tot} |")
    return "\n".join(L) + "\n"


def main() -> None:
    argparse.ArgumentParser(description=__doc__).parse_args()
    TABLES_DIR.mkdir(parents=True, exist_ok=True)
    out = TABLES_DIR / "single_change_summary.md"
    out.write_text(build())
    print(f"  wrote {out}")


if __name__ == "__main__":
    main()
